const Products = [
  {
    id: 1,
    name: "Red Dress",
    category: "Dresses",
    price: 500,
    discount: 20,
    image:
      "https://m.media-amazon.com/images/I/71UK6gd7LVL._AC_UL480_FMwebp_QL65_.jpg",
    description: "Beautiful red evening dress.",
    limited: true,
    rating: 4.3,
  },
  {
    id: 2,
    name: "Blue Dress",
    category: "Dresses",
    price: 450,
    discount: 15,
    image:
      "https://m.media-amazon.com/images/I/61MwxbBTeAL._AC_UL480_FMwebp_QL65_.jpg",
    description: "Elegant blue cocktail dress.",
    limited: false,
    rating: 4.3,
  },
  {
    id: 3,
    name: "Green Dress",
    category: "Dresses",
    price: 550,
    discount: 25,
    image:
      "https://m.media-amazon.com/images/I/61hIDPx+lML._AC_UL480_FMwebp_QL65_.jpg",
    description: "Charming green party dress.",
    limited: true,
    rating: 4.3,
  },
  {
    id: 4,
    name: "Black Dress",
    category: "Dresses",
    price: 600,
    discount: 30,
    image:
      "https://m.media-amazon.com/images/I/61iDvw7wxML._AC_UL480_FMwebp_QL65_.jpg",
    description: "Classic little black dress.",
    limited: false,
    rating: 4.3,
  },
  {
    id: 5,
    name: "Yellow Dress",
    category: "Dresses",
    price: 480,
    discount: 10,
    image:
      "https://m.media-amazon.com/images/I/71RPYSvOCbL._AC_UL480_FMwebp_QL65_.jpg",
    description: "Bright and sunny yellow dress.",
    limited: false,
    rating: 4.3,
  },
  {
    id: 6,
    name: "Smartphone X",
    category: "Mobiles",
    price: 15000,
    discount: 10,
    image:
      "https://m.media-amazon.com/images/I/71IIxHUk3pL._AC_UY327_FMwebp_QL65_.jpg",
    description: "High-performance smartphone with great camera.",
    limited: true,
    rating: 4.3,
  },
  {
    id: 7,
    name: "Smartphone Y",
    category: "Mobiles",
    price: 18000,
    discount: 5,
    image:
      "https://m.media-amazon.com/images/I/81PjX4nMY5L._AC_UY327_FMwebp_QL65_.jpg",
    description: "Powerful device with long battery life.",
    limited: false,
    rating: 4.3,
  },
  {
    id: 8,
    name: "Smartphone Z",
    category: "Mobiles",
    price: 22000,
    discount: 15,
    image:
      "https://m.media-amazon.com/images/I/71tqCUlv-xL._AC_UY327_FMwebp_QL65_.jpg",
    description: "Sleek design with high-resolution display.",
    limited: false,
    rating: 4.3,
  },
  {
    id: 9,
    name: "Budget Phone A1",
    category: "Mobiles",
    price: 8000,
    discount: 0,
    image:
      "https://m.media-amazon.com/images/I/71PqycNARKL._AC_UY327_FMwebp_QL65_.jpg",
    description: "Affordable phone with essential features.",
    limited: true,
    rating: 4.3,
  },
  {
    id: 10,
    name: "Gaming Phone Pro",
    category: "Mobiles",
    price: 25000,
    discount: 20,
    image:
      "https://m.media-amazon.com/images/I/81FZXIvAgdL._AC_UY327_FMwebp_QL65_.jpg",
    description: "Optimized for gaming with high refresh rate screen.",
    limited: false,
    rating: 4.3,
  },
  {
    id: 11,
    name: "Laptop Pro",
    category: "Laptops",
    price: 55000,
    discount: 15,
    image:
      "https://m.media-amazon.com/images/I/71CQ2SFwyZL._AC_UY327_FMwebp_QL65_.jpg",
    description: "High-end laptop for professionals.",
    limited: true,
    rating: 4.3,
  },
  {
    id: 12,
    name: "Gaming Laptop",
    category: "Laptops",
    price: 70000,
    discount: 20,
    image:
      "https://m.media-amazon.com/images/I/61keRkmSGBL._AC_UY327_FMwebp_QL65_.jpg",
    description: "Dedicated graphics for smooth gaming.",
    limited: false,
    rating: 4.3,
  },
  {
    id: 13,
    name: "Student Laptop",
    category: "Laptops",
    price: 35000,
    discount: 5,
    image:
      "https://m.media-amazon.com/images/I/712wKKTsDbL._AC_UY327_FMwebp_QL65_.jpg",
    description: "Budget-friendly laptop for students.",
    limited: true,
    rating: 4.3,
  },
  {
    id: 14,
    name: "Business Laptop",
    category: "Laptops",
    price: 60000,
    discount: 10,
    image:
      "https://m.media-amazon.com/images/I/71+gQ9gOTuL._AC_UY327_FMwebp_QL65_.jpg",
    description: "Secure and reliable for office use.",
    limited: true,
    rating: 4.3,
  },
  {
    id: 15,
    name: "Ultra Slim Laptop",
    category: "Laptops",
    price: 48000,
    discount: 12,
    image:
      "https://m.media-amazon.com/images/I/61fsBFww9DL._AC_UY327_FMwebp_QL65_.jpg",
    description: "Lightweight and portable design.",
    limited: false,
    rating: 4.3,
  },
  {
    id: 16,
    name: "Fitness Watch",
    category: "Watches",
    price: 2500,
    discount: 10,
    image:
      "https://m.media-amazon.com/images/I/816eXKgDfIL._AC_UL480_FMwebp_QL65_.jpg",
    description: "Track your steps, calories, and sleep.",
    limited: false,
    rating: 4.3,
  },
  {
    id: 17,
    name: "Luxury Watch",
    category: "Watches",
    price: 15000,
    discount: 20,
    image:
      "https://m.media-amazon.com/images/I/71MlmOso55L._AC_UL480_FMwebp_QL65_.jpg",
    description: "Elegant timepiece with leather strap.",
    limited: false,
    rating: 4.3,
  },
  {
    id: 18,
    name: "Digital Watch",
    category: "Watches",
    price: 1200,
    discount: 5,
    image:
      "https://m.media-amazon.com/images/I/61XESKwObcL._AC_UL480_FMwebp_QL65_.jpg",
    description: "Simple and reliable digital display.",
    limited: false,
    rating: 4.3,
  },
  {
    id: 19,
    name: "Analog Watch",
    category: "Watches",
    price: 1800,
    discount: 8,
    image:
      "https://m.media-amazon.com/images/I/61akt30bJsL._AC_UL480_FMwebp_QL65_.jpg",
    description: "Classic analog watch with metal strap.",
    limited: true,
    rating: 4.3,
  },
  {
    id: 20,
    name: "Smartwatch Max",
    category: "Watches",
    price: 3200,
    discount: 15,
    image:
      "https://m.media-amazon.com/images/I/81OmI2S7tUL._AC_UL480_FMwebp_QL65_.jpg",
    description: "Full touchscreen with app support.",
    limited: true,
    rating: 4.3,
  },
];
export default Products;
